---

- name: Installing prerequisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: true
  become: true

- name: Add gpg docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: true
  become: true

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: true
  become: true

- name: Enable Docker servive
  systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
  become: true

- name: Addding user {{ ansible_user }} to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
